GET https://test-railway-fastapi-backend-production.up.railway.app/ HTTP/1.1
content-type: application/json

###
POST https://test-railway-fastapi-backend-production.up.railway.app/data HTTP/1.1
content-type: application/json

{
  "image":"test",
}

###
POST http://127.0.0.1:8000/api/external HTTP/1.1
content-type: application/json

###
GET http://127.0.0.1:8000/api/user/1 HTTP/1.1
content-type: application/json

###
POST http://127.0.0.1:8000/rover/operations/2 HTTP/1.1

###
POST http://127.0.0.1:8000/rover HTTP/1.1
content-type: application/json

{
  "roverId":2 ,
  "randomId":1234 ,
  "batteryStatus":12.3 ,
  "temp": 12.3,
  "humidity": 12.3,
  "imageData": "data"
}

###
POST http://127.0.0.1:8000/rover HTTP/1.1
content-type: application/json

{
  "roverId":1 ,
  "randomId":1234 ,
  "batteryStatus":12.3 ,
  "temp": 12.3,
  "humidity": 12.3,
  "imageData": {
    "mime": "image/png",
    "data": "test"
  }
}

###
POST https://axum-jwt-static-page-template-4gs7.shuttle.app/rover/operations/2 HTTP/1.1

###
POST https://axum-jwt-static-page-template-4gs7.shuttle.app/rover/status/1 HTTP/1.1

###
POST https://axum-jwt-static-page-template-4gs7.shuttle.app/rover HTTP/1.1
content-type: application/json

{
  "roverId":1 ,
  "randomId":1234 ,
  "batteryStatus":12.3 ,
  "temp": 12.3,
  "humidity": 12.3,
  "imageData": {
    "mime": "image/png",
    "data": "test"
  }
}

###
# POST http://127.0.0.1:8000/test/rover HTTP/1.1
POST https://axum-jwt-static-page-template-4gs7.shuttle.app/test/rover HTTP/1.1
content-type: application/json

{
  "roverId":1 ,
  "randomId":1234 ,
  "batteryStatus":12.3 ,
  "temp": 12.3,
  "humidity": 12.3,
  "imageData": {
    "mime": "image/png",
    "data": "test"
  }
}